export const GET_PRODUCTS_TO_SHOP = "GET_PRODUCTS_TO_SHOP";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL";

export const QUERY_PRODUCTS_SUCCEEDED = "QUERY_PRODUCTS_SUCCEEDED";
export const QUERY_PRODUCTS_FAILED = "QUERY_PRODUCTS_FAILED";
export const QUERY_PRODUCTS_STARTED = "QUERY_PRODUCTS_STARTED";

export const MODIFY_CART_SUCCEEDED = "MODIFY_CART_SUCCEEDED";
export const FLASH_MESSAGE = "FLASH_MESSAGE";

export const MODIFY_SHOPLIST_SUCCEEDED = "MODIFY_SHOPLIST_SUCCEEDED";
export const DELETE_SHOPLIST_ITEM = "DELETE_SHOPLIST_ITEM";
export const ADD_ITEM_TO_SHOPLIST = "ADD_ITEM_TO_SHOPLIST";
